todo/urls.py
from django.urls import path

from todo.views import (
    TaskListView,
    TagListView,
    TaskCreateView,
    TagCreateView,
    TagUpdateView,
    TaskUpdateView,
    TaskDeleteView,
    TagDeleteView,
    toggle_task_done,
)

urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
    path("task-create/", TaskCreateView.as_view(), name="task-create"),
    path("task/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("task/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("task/<int:pk>/toggle-done/", toggle_task_done, name="toggle-task-done"),
]

app_name = "todo"

todo_list_task/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("", include("todo.urls", namespace="todo")),
]

todo/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(blank=True, null=True)
    done = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks")

todo/forms.py
from django import forms

from todo.models import Task, Tag


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple(),
    )
    deadline = forms.DateTimeField(
        widget=forms.DateTimeInput(attrs={"type": "datetime-local"}),
        input_formats=["%Y-%m-%dT%H:%M"],
        required=False,
    )

    class Meta:
        model = Task
        fields = ("content", "tags", "deadline")

todo/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views import generic

from todo.forms import TaskForm
from todo.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task
    context_object_name = "task_list"

    def get_queryset(self):
        return Task.objects.order_by("done", "-created_at").prefetch_related("tags")


class TagListView(generic.ListView):
    model = Tag
    context_object_name = "tag_list"


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo:task-list")


class TagCreateView(generic.CreateView):
    model = Tag
    fields = ["name"]
    success_url = reverse_lazy("todo:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = ["name"]
    success_url = reverse_lazy("todo:tag-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo:task-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo:tag-list")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo:task-list")


def toggle_task_done(request, pk):
    task = get_object_or_404(Task, id=pk)
    task.done = not task.done
    task.save()
    return HttpResponseRedirect(reverse_lazy("todo:task-list"))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>TODO</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
        crossorigin="anonymous">
  {% load static %}
</head>
<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">

      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}

    </div>
    <div class="col-sm-10 ">

      {% block content %}
      {% endblock %}

    </div>
  </div>
</div>
</body>
</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'todo:task-list' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'todo:tag-list' %}">Tags</a></li>
</ul>

templates/todo/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag?</h1>
  <p>Are you sure you want to delete tag <strong>{{ tag.name }}</strong>?</p>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/todo/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo/tag_list.html
{% extends "base.html" %}

{% block content %}
  <div class="d-flex justify-content-between align-items-center">
    <h1>Tags</h1>
    <a class="btn btn-primary" href="{% url 'todo:tag-create' %}">Add</a>
  </div>
  {% if tag_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
      {% for tag in tag_list %}
        <tr>
          <td>{{ tag.name }}</td>
          <td><a class="btn btn-primary" href="{% url 'todo:tag-update' pk=tag.id %}">Update</a></td>
          <td><a class="btn btn-danger" href="{% url 'todo:tag-delete' pk=tag.id %}">Delete</a></td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no tags.</p>
  {% endif %}
{% endblock %}

templates/todo/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task?</h1>
  <p>Are you sure you want to delete task: <strong>{{ task.content }}</strong>?</p>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/todo/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo/task_list.html
{% extends "base.html" %}

{% block content %}
  <div class="d-flex justify-content-between align-items-center">
    <h1>TODO list</h1>
    <a class="btn btn-primary" href="{% url 'todo:task-create' %}">Add new task</a>
  </div>

  {% if task_list %}
    <ul>
      {% for task in task_list %}
        <li class="d-flex justify-content-between align-items-center">
          <div>
            <strong>{{ task.content }}</strong>
            {% if task.done %}
              <span style="color: #00ff00;"><strong>Done</strong></span>
            {% else %}
              <span style="color: #800000;"><strong>Not done</strong></span>
            {% endif %}
            <br>

            Created: {{ task.created_at }}
            {% if task.deadline %}
              <span style="color: #800000;"><strong>Deadline: {{ task.deadline }}</strong></span>
            {% endif %}<br>

            Tags:
            {% if task.tags.all %}
              {% for tag in task.tags.all %}
                {{ tag.name }}
              {% endfor %}
            {% else %}
              <span>No tags</span>
            {% endif %}
            <a href="{% url 'todo:task-update' pk=task.id %}">Update</a>
            <a href="{% url 'todo:task-delete' pk=task.id %}">Delete</a>
          </div>

          <div class="ml-auto">
            {% if task.done %}
              <a class="btn btn-secondary" href="{% url 'todo:toggle-task-done' pk=task.id %}">Undo</a>
            {% else %}
              <a class="btn btn-success" href="{% url 'todo:toggle-task-done' pk=task.id %}">Complete</a>
            {% endif %}
          </div>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no tasks.</p>
  {% endif %}

{% endblock %}